name: CI

'on':
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org

jobs:
  verify-goimports:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          stable: true

      - uses: actions/checkout@v2

      - name: verify goimports
        run: |
          files=$(go run golang.org/x/tools/cmd/goimports -format-only -l .)
          # Sadly goimports doesn't use exit codes
          if [[ -n "${files}" ]]; then
            echo "::error ::goimports should be run on these files:"
            echo "${files}"
            exit 1
          fi

  verify-gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          stable: true

      - uses: actions/checkout@v2

      - run: dev/format-gomod

      - run: |
          changes=$(git status --porcelain)
          if [[ -n "${changes}" ]]; then
            echo "::error Changes detected from dev/format-gomod:"
            echo "::error (You may need to run go clean -cache -modcache)"
            git diff | head -n60
            echo "${changes}"
            exit 1
          fi

  kind-e2e:
    name: Test with a Kind cluster
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - name: Install latest version of Kind
      run: |
        go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        kind create cluster --config .github/workflows/kind-config.yaml
    - name: Run some sanity checks
      # kubectl is already installed on the Github Ubuntu worker
      run: |
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces -o wide
        kubectl get services --all-namespaces -o wide
