name: CI

'on':
  - push
  - pull_request

env:
  GOPROXY: https://proxy.golang.org

jobs:
  verify-goimports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: verify-goimports
        run: dev/ci/presubmits/verify-goimports


  verify-gomod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: verify-gomod
        run: dev/ci/presubmits/verify-gomod

  kind-e2e:
    name: Test with a Kind cluster
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Install latest version of Kind
      run: |
        go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        kind create cluster --config .github/workflows/kind-config.yaml
    - name: Run some sanity checks
      # kubectl is already installed on the Github Ubuntu worker
      run: |
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces -o wide
        kubectl get services --all-namespaces -o wide
