name: 'Tag Release'

on:
  push:
    branches:
      - master
      - 'release-*'
    paths:
      - version/*

jobs:
  tag-release:
    if: ${{ github.repository == 'kubernetes-sigs/kubebuilder-declarative-pattern' }}
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: dev/bots/projectbots/tag-release
